version: '3'

services:
    web:
      container_name: fitquest
      build: .
      env_file: .env
      restart: always
      ports:
          - "127.0.0.1:8080:8080"
      depends_on:
          - mariadb
      links:
          - mariadb

    mariadb:
      container_name: fitquestdb
      image: bitnami/mariadb
      env_file: .env
      restart: always
      ports:
          - 3306:3306
      volumes:
          - fitquest_data:/bitnami
volumes:
    fitquest_data:
